//! Declarative list of all flags → keys (one source of truth).
//! Keep docs short; detailed docs live in module docs.

use super::options_core::{Arity, Registry, Spec, ValueKind};

pub static SPECS: &[Spec] = &[
    // --------- Core utility
    Spec { flag: "-options_file", key: "options_file", arity: Arity::One, kind: ValueKind::Str, doc: "Read more options from file" },

    // --------- KSP
    Spec { flag: "-ksp_type",       key: "ksp_type",       arity: Arity::One, kind: ValueKind::Str,   doc: "cg, gmres, bicgstab, ..." },
    Spec { flag: "-ksp_rtol",       key: "ksp_rtol",       arity: Arity::One, kind: ValueKind::Float, doc: "relative tol" },
    Spec { flag: "-ksp_atol",       key: "ksp_atol",       arity: Arity::One, kind: ValueKind::Float, doc: "absolute tol" },
    Spec { flag: "-ksp_dtol",       key: "ksp_dtol",       arity: Arity::One, kind: ValueKind::Float, doc: "divergence tol" },
    Spec { flag: "-ksp_max_it",     key: "ksp_max_it",     arity: Arity::One, kind: ValueKind::UInt,  doc: "max iterations" },
    Spec { flag: "-ksp_gmres_restart", key: "ksp_gmres_restart", arity: Arity::One, kind: ValueKind::UInt, doc: "GMRES restart" },
    Spec { flag: "-ksp_pc_side",    key: "ksp_pc_side",    arity: Arity::One, kind: ValueKind::Str,   doc: "left|right|symmetric" },
    Spec { flag: "-matrix",         key: "matrix",         arity: Arity::One, kind: ValueKind::Str,   doc: "matrix file" },
    Spec { flag: "-rhs",            key: "rhs",            arity: Arity::One, kind: ValueKind::Str,   doc: "rhs file" },
    Spec { flag: "-ksp_min_iter",   key: "ksp_min_iter",   arity: Arity::One, kind: ValueKind::UInt,  doc: "min iter before check" },
    Spec { flag: "-ksp_cf_tol",     key: "ksp_cf_tol",     arity: Arity::One, kind: ValueKind::Float, doc: "stagnation CF tol" },
    Spec { flag: "-ksp_skip_real_r_check", key: "ksp_skip_real_r_check", arity: Arity::Zero, kind: ValueKind::Bool, doc: "toggle real-residual check" },
    Spec { flag: "-ksp_epsmac",     key: "ksp_epsmac",     arity: Arity::One, kind: ValueKind::Float, doc: "IEEE epsilon" },
    Spec { flag: "-ksp_guard_zero_residual", key: "ksp_guard_zero_residual", arity: Arity::One, kind: ValueKind::Float, doc: "guard for zero residual" },

    // --------- PC (subset shown; we include all below)
    Spec { flag: "-pc_type",             key: "pc_type",             arity: Arity::One, kind: ValueKind::Str,   doc: "jacobi, ilu, amg, ..." },
    Spec { flag: "-pc_ilu_levels",       key: "pc_ilu_levels",       arity: Arity::One, kind: ValueKind::UInt,  doc: "ILU levels (legacy)" },
    Spec { flag: "-pc_chebyshev_degree", key: "pc_chebyshev_degree", arity: Arity::One, kind: ValueKind::UInt,  doc: "Chebyshev degree" },
    Spec { flag: "-pc_ilut_drop_tol",    key: "pc_ilut_drop_tol",    arity: Arity::One, kind: ValueKind::Float, doc: "ILUT drop tol" },
    Spec { flag: "-pc_ilut_max_fill",    key: "pc_ilut_max_fill",    arity: Arity::One, kind: ValueKind::UInt,  doc: "ILUT max fill" },
    Spec { flag: "-pc_ilut_perm_tol",    key: "pc_ilut_perm_tol",    arity: Arity::One, kind: ValueKind::Float, doc: "ILUTP pivot tol" },
    Spec { flag: "-pc_reorder",          key: "pc_reorder",          arity: Arity::One, kind: ValueKind::Str,   doc: "none|colamd|amd|rcm|cuthill_mckee" },
    Spec { flag: "-pc_scaling",          key: "pc_scaling",          arity: Arity::One, kind: ValueKind::Str,   doc: "none|diagonal|symmetric" },
    Spec { flag: "-pc_asm_overlap",      key: "pc_asm_overlap",      arity: Arity::One, kind: ValueKind::UInt,  doc: "ASM overlap" },
    Spec { flag: "-pc_asm_subdomains",   key: "pc_asm_subdomains",   arity: Arity::One, kind: ValueKind::Str,   doc: "CSV indices" },
    Spec { flag: "-pc_asm_inner_pc",     key: "pc_asm_inner_pc",     arity: Arity::One, kind: ValueKind::Str,   doc: "jacobi|ilu|ilut|ilutp" },
    Spec { flag: "-pc_chebyshev_lambda_min", key: "pc_chebyshev_lambda_min", arity: Arity::One, kind: ValueKind::Float, doc: "lambda_min" },
    Spec { flag: "-pc_chebyshev_lambda_max", key: "pc_chebyshev_lambda_max", arity: Arity::One, kind: ValueKind::Float, doc: "lambda_max" },
    Spec { flag: "-pc_amg_levels",           key: "pc_amg_levels",           arity: Arity::One, kind: ValueKind::UInt,  doc: "AMG levels" },
    Spec { flag: "-pc_amg_strength_threshold", key: "pc_amg_strength_threshold", arity: Arity::One, kind: ValueKind::Float, doc: "strength threshold" },
    Spec { flag: "-pc_amg_nu_pre",           key: "pc_amg_nu_pre",           arity: Arity::One, kind: ValueKind::UInt,  doc: "pre-smoothing iters" },
    Spec { flag: "-pc_amg_nu_post",          key: "pc_amg_nu_post",          arity: Arity::One, kind: ValueKind::UInt,  doc: "post-smoothing iters" },
    Spec { flag: "-pc_amg_coarse_threshold", key: "pc_amg_coarse_threshold", arity: Arity::One, kind: ValueKind::UInt,  doc: "coarse threshold" },
    Spec { flag: "-pc_amg_max_coarse_size",  key: "pc_amg_max_coarse_size",  arity: Arity::One, kind: ValueKind::UInt,  doc: "max coarse size" },
    Spec { flag: "-pc_amg_min_coarse_size",  key: "pc_amg_min_coarse_size",  arity: Arity::One, kind: ValueKind::UInt,  doc: "min coarse size" },
    Spec { flag: "-pc_amg_truncation_factor", key: "pc_amg_truncation_factor", arity: Arity::One, kind: ValueKind::Float, doc: "interp truncation" },
    Spec { flag: "-pc_amg_max_elements_per_row", key: "pc_amg_max_elements_per_row", arity: Arity::One, kind: ValueKind::UInt, doc: "max elts/row" },
    Spec { flag: "-pc_amg_interpolation_truncation", key: "pc_amg_interpolation_truncation", arity: Arity::One, kind: ValueKind::Float, doc: "interp truncation" },
    Spec { flag: "-pc_amg_coarsen_type",     key: "pc_amg_coarsen_type",     arity: Arity::One, kind: ValueKind::Str,   doc: "rs|hmis|pmis|falgout" },
    Spec { flag: "-pc_amg_interp_type",      key: "pc_amg_interp_type",      arity: Arity::One, kind: ValueKind::Str,   doc: "classical|direct|..." },
    Spec { flag: "-pc_amg_relax_type",       key: "pc_amg_relax_type",       arity: Arity::One, kind: ValueKind::Str,   doc: "jacobi|gs|...|chebyshev" },
    Spec { flag: "-pc_amg_logging_level",    key: "pc_amg_logging_level",    arity: Arity::One, kind: ValueKind::UInt,  doc: "0..2" },
    Spec { flag: "-pc_amg_print_level",      key: "pc_amg_print_level",      arity: Arity::One, kind: ValueKind::UInt,  doc: "0..2" },
    Spec { flag: "-pc_amg_tolerance",        key: "pc_amg_tolerance",        arity: Arity::One, kind: ValueKind::Float, doc: "AMG tol (standalone)" },
    Spec { flag: "-pc_amg_max_iterations",   key: "pc_amg_max_iterations",   arity: Arity::One, kind: ValueKind::UInt,  doc: "AMG max iters" },
    Spec { flag: "-pc_amg_min_iterations",   key: "pc_amg_min_iterations",   arity: Arity::One, kind: ValueKind::UInt,  doc: "AMG min iters" },
    Spec { flag: "-pc_amg_ieee_checks",      key: "pc_amg_ieee_checks",      arity: Arity::Zero, kind: ValueKind::Bool, doc: "enable IEEE checks" },
    Spec { flag: "-pc_amg_optimize_workspace", key: "pc_amg_optimize_workspace", arity: Arity::Zero, kind: ValueKind::Bool, doc: "optimize workspace" },
    Spec { flag: "-pc_chain",                key: "pc_chain",                arity: Arity::One, kind: ValueKind::Str,   doc: "comma-separated chain" },
    Spec { flag: "-pc_reuse_policy",        key: "pc_reuse_policy",        arity: Arity::One, kind: ValueKind::Str,   doc: "never|reuse_numeric|auto" },

    // ILU block
    Spec { flag: "-pc_ilu_type",             key: "pc_ilu_type",             arity: Arity::One, kind: ValueKind::Str,   doc: "ilu0|iluk|ilut|..." },
    Spec { flag: "-pc_ilu_level_of_fill",    key: "pc_ilu_level_of_fill",    arity: Arity::One, kind: ValueKind::UInt,  doc: "ILU(k) level" },
    Spec { flag: "-pc_ilu_max_fill_per_row", key: "pc_ilu_max_fill_per_row", arity: Arity::One, kind: ValueKind::UInt,  doc: "max nnz/row" },
    Spec { flag: "-pc_ilu_offdiag_drop_tolerance", key: "pc_ilu_offdiag_drop_tolerance", arity: Arity::One, kind: ValueKind::Float, doc: "offdiag drop tol" },
    Spec { flag: "-pc_ilu_schur_drop_tolerance",   key: "pc_ilu_schur_drop_tolerance",   arity: Arity::One, kind: ValueKind::Float, doc: "Schur drop tol" },
    Spec { flag: "-pc_ilu_reordering_type",  key: "pc_ilu_reordering_type",  arity: Arity::One, kind: ValueKind::Str,   doc: "none|rcm|amd|natural" },
    Spec { flag: "-pc_ilu_triangular_solve", key: "pc_ilu_triangular_solve", arity: Arity::One, kind: ValueKind::Str,   doc: "exact|iterative" },
    Spec { flag: "-pc_ilu_lower_jacobi_iters", key: "pc_ilu_lower_jacobi_iters", arity: Arity::One, kind: ValueKind::UInt, doc: "lower Jacobi iters" },
    Spec { flag: "-pc_ilu_upper_jacobi_iters", key: "pc_ilu_upper_jacobi_iters", arity: Arity::One, kind: ValueKind::UInt, doc: "upper Jacobi iters" },
    Spec { flag: "-pc_ilu_tolerance",        key: "pc_ilu_tolerance",        arity: Arity::One, kind: ValueKind::Float, doc: "iterative solve tol" },
    Spec { flag: "-pc_ilu_max_iterations",   key: "pc_ilu_max_iterations",   arity: Arity::One, kind: ValueKind::UInt,  doc: "iterative solve max iters" },
    Spec { flag: "-pc_ilu_logging_level",    key: "pc_ilu_logging_level",    arity: Arity::One, kind: ValueKind::UInt,  doc: "0..2" },
    Spec { flag: "-pc_ilu_print_level",      key: "pc_ilu_print_level",      arity: Arity::One, kind: ValueKind::UInt,  doc: "0..2" },
    Spec { flag: "-pc_ilu_ieee_checks",      key: "pc_ilu_ieee_checks",      arity: Arity::Zero, kind: ValueKind::Bool, doc: "enable IEEE checks" },
    Spec { flag: "-pc_ilu_pivot_monitoring", key: "pc_ilu_pivot_monitoring", arity: Arity::Zero, kind: ValueKind::Bool, doc: "monitor pivots" },
    Spec { flag: "-pc_ilu_optimize_workspace", key: "pc_ilu_optimize_workspace", arity: Arity::Zero, kind: ValueKind::Bool, doc: "optimize workspace" },
    Spec { flag: "-pc_ilu_pivot_threshold",  key: "pc_ilu_pivot_threshold",  arity: Arity::One, kind: ValueKind::Float, doc: "pivot threshold" },

    // SuperLU_DIST
    Spec { flag: "-pc_superlu_pivot_threshold", key: "pc_superlu_pivot_threshold", arity: Arity::One, kind: ValueKind::Float, doc: "pivot threshold (0..1)" },
    Spec { flag: "-pc_superlu_replace_tiny_pivot", key: "pc_superlu_replace_tiny_pivot", arity: Arity::Zero, kind: ValueKind::Bool, doc: "replace tiny pivots" },
    Spec { flag: "-pc_superlu_print_level",  key: "pc_superlu_print_level",  arity: Arity::One, kind: ValueKind::UInt,  doc: "0..2" },
    Spec { flag: "-pc_superlu_process_grid", key: "pc_superlu_process_grid", arity: Arity::Two, kind: ValueKind::Pair("uint","uint"), doc: "grid rows cols" },
    Spec { flag: "-pc_superlu_column_permutation", key: "pc_superlu_column_permutation", arity: Arity::One, kind: ValueKind::Str, doc: "col perm strategy" },
    Spec { flag: "-pc_superlu_row_permutation",    key: "pc_superlu_row_permutation",    arity: Arity::One, kind: ValueKind::Str, doc: "row perm strategy" },
    Spec { flag: "-pc_superlu_iterative_refinement", key: "pc_superlu_iterative_refinement", arity: Arity::One, kind: ValueKind::Str, doc: "iterative refinement" },
    Spec { flag: "-pc_superlu_static_pivoting", key: "pc_superlu_static_pivoting", arity: Arity::Zero, kind: ValueKind::Bool, doc: "static pivoting" },
    Spec { flag: "-pc_superlu_panel_size",    key: "pc_superlu_panel_size",    arity: Arity::One, kind: ValueKind::UInt,  doc: "panel size" },
    Spec { flag: "-pc_superlu_enable_3d_factorization", key: "pc_superlu_enable_3d_factorization", arity: Arity::Zero, kind: ValueKind::Bool, doc: "enable 3D" },
    Spec { flag: "-pc_superlu_process_grid_3d_depth",   key: "pc_superlu_process_grid_3d_depth", arity: Arity::One, kind: ValueKind::UInt, doc: "3D depth" },
    Spec { flag: "-pc_superlu_memory_tradeoff_factor",  key: "pc_superlu_memory_tradeoff_factor", arity: Arity::One, kind: ValueKind::Float, doc: "memory tradeoff" },
    Spec { flag: "-pc_superlu_max_concurrent_panels",   key: "pc_superlu_max_concurrent_panels", arity: Arity::One, kind: ValueKind::UInt, doc: "max panels" },
    Spec { flag: "-pc_superlu_async_panel_updates",     key: "pc_superlu_async_panel_updates",   arity: Arity::Zero, kind: ValueKind::Bool, doc: "async panels" },
    Spec { flag: "-pc_superlu_workspace_memory_limit",  key: "pc_superlu_workspace_memory_limit", arity: Arity::One, kind: ValueKind::UInt, doc: "MB limit" },
    Spec { flag: "-pc_superlu_aggressive_memory_reuse", key: "pc_superlu_aggressive_memory_reuse", arity: Arity::Zero, kind: ValueKind::Bool, doc: "aggressive reuse" },
    Spec { flag: "-pc_superlu_preallocation_strategy",  key: "pc_superlu_preallocation_strategy", arity: Arity::One, kind: ValueKind::Str, doc: "none|matrix_size|..." },
];

pub fn registry() -> Registry { Registry::new(SPECS) }
